site_name: Datalchemy
repo_url: https://github.com/Bruno-Gomes-QA/datalchemy
repo_name: Bruno-Gomes-QA/datalchemy
edit_uri: tree/master/docs

theme:
  name: material

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [datalchemy]