// AUTO-GENERATED BY tools/gen_faker_catalog.rs. DO NOT EDIT.
use rand::RngCore;

use crate::faker_rs::locales::LocaleKey;

use crate::generators::GeneratedValue;

use fake::Fake;

pub struct AliasEntry {
    pub id: &'static str,
    pub target: &'static str,
    pub locales: &'static [LocaleKey],
}

pub const GENERATED_IDS: &[&str] = &[
    "faker.address.raw.BuildingNumber",
    "faker.address.raw.CityName",
    "faker.address.raw.CityPrefix",
    "faker.address.raw.CitySuffix",
    "faker.address.raw.CountryCode",
    "faker.address.raw.CountryName",
    "faker.address.raw.Geohash",
    "faker.address.raw.Latitude",
    "faker.address.raw.Longitude",
    "faker.address.raw.PostCode",
    "faker.address.raw.SecondaryAddress",
    "faker.address.raw.SecondaryAddressType",
    "faker.address.raw.StateAbbr",
    "faker.address.raw.StateName",
    "faker.address.raw.StreetName",
    "faker.address.raw.StreetSuffix",
    "faker.address.raw.TimeZone",
    "faker.address.raw.ZipCode",
    "faker.barcode.raw.Isbn",
    "faker.barcode.raw.Isbn10",
    "faker.barcode.raw.Isbn13",
    "faker.boolean.raw.Boolean",
    "faker.chrono.raw.Date",
    "faker.chrono.raw.DateTime",
    "faker.chrono.raw.DateTimeAfter",
    "faker.chrono.raw.DateTimeBefore",
    "faker.chrono.raw.DateTimeBetween",
    "faker.chrono.raw.Duration",
    "faker.chrono.raw.Time",
    "faker.color.raw.Color",
    "faker.color.raw.HexColor",
    "faker.color.raw.HslColor",
    "faker.color.raw.HslaColor",
    "faker.color.raw.RgbColor",
    "faker.color.raw.RgbaColor",
    "faker.company.raw.Bs",
    "faker.company.raw.BsAdj",
    "faker.company.raw.BsNoun",
    "faker.company.raw.BsVerb",
    "faker.company.raw.Buzzword",
    "faker.company.raw.BuzzwordMiddle",
    "faker.company.raw.BuzzwordTail",
    "faker.company.raw.CatchPhrase",
    "faker.company.raw.CompanyName",
    "faker.company.raw.CompanySuffix",
    "faker.company.raw.Industry",
    "faker.company.raw.Profession",
    "faker.creditcard.raw.CreditCardNumber",
    "faker.currency.raw.CurrencyCode",
    "faker.currency.raw.CurrencyName",
    "faker.currency.raw.CurrencySymbol",
    "faker.filesystem.raw.DirPath",
    "faker.filesystem.raw.FileExtension",
    "faker.filesystem.raw.FileName",
    "faker.filesystem.raw.FilePath",
    "faker.filesystem.raw.MimeType",
    "faker.filesystem.raw.Semver",
    "faker.filesystem.raw.SemverStable",
    "faker.filesystem.raw.SemverUnstable",
    "faker.finance.raw.Bic",
    "faker.finance.raw.Isin",
    "faker.http.raw.RfcStatusCode",
    "faker.http.raw.ValidStatusCode",
    "faker.internet.raw.DomainSuffix",
    "faker.internet.raw.FreeEmail",
    "faker.internet.raw.FreeEmailProvider",
    "faker.internet.raw.IP",
    "faker.internet.raw.IPv4",
    "faker.internet.raw.IPv6",
    "faker.internet.raw.MACAddress",
    "faker.internet.raw.Password",
    "faker.internet.raw.SafeEmail",
    "faker.internet.raw.UserAgent",
    "faker.internet.raw.Username",
    "faker.job.raw.Field",
    "faker.job.raw.Position",
    "faker.job.raw.Seniority",
    "faker.job.raw.Title",
    "faker.lorem.raw.Paragraph",
    "faker.lorem.raw.Paragraphs",
    "faker.lorem.raw.Sentence",
    "faker.lorem.raw.Sentences",
    "faker.lorem.raw.Word",
    "faker.lorem.raw.Words",
    "faker.markdown.raw.BlockQuoteMultiLine",
    "faker.markdown.raw.BlockQuoteSingleLine",
    "faker.markdown.raw.BoldWord",
    "faker.markdown.raw.BulletPoints",
    "faker.markdown.raw.Code",
    "faker.markdown.raw.ItalicWord",
    "faker.markdown.raw.Link",
    "faker.markdown.raw.ListItems",
    "faker.name.raw.FirstName",
    "faker.name.raw.LastName",
    "faker.name.raw.Name",
    "faker.name.raw.NameWithTitle",
    "faker.name.raw.Suffix",
    "faker.name.raw.Title",
    "faker.number.raw.Digit",
    "faker.phone_number.raw.CellNumber",
    "faker.phone_number.raw.PhoneNumber",
    "faker.time.raw.Date",
    "faker.time.raw.DateTime",
    "faker.time.raw.DateTimeAfter",
    "faker.time.raw.DateTimeBefore",
    "faker.time.raw.DateTimeBetween",
    "faker.time.raw.Duration",
    "faker.time.raw.Time",
];

pub const PARAMETERIZED_IDS: &[&str] = &[
    "faker.address.raw.Geohash",
    "faker.boolean.raw.Boolean",
    "faker.chrono.raw.DateTimeAfter",
    "faker.chrono.raw.DateTimeBefore",
    "faker.chrono.raw.DateTimeBetween",
    "faker.internet.raw.Password",
    "faker.lorem.raw.Paragraph",
    "faker.lorem.raw.Paragraphs",
    "faker.lorem.raw.Sentence",
    "faker.lorem.raw.Sentences",
    "faker.lorem.raw.Words",
    "faker.markdown.raw.BlockQuoteMultiLine",
    "faker.markdown.raw.BlockQuoteSingleLine",
    "faker.markdown.raw.BulletPoints",
    "faker.markdown.raw.Code",
    "faker.markdown.raw.ListItems",
    "faker.time.raw.DateTimeAfter",
    "faker.time.raw.DateTimeBefore",
    "faker.time.raw.DateTimeBetween",
];

pub const ALL_IDS: &[&str] = &[
    "faker.address.raw.BuildingNumber",
    "faker.address.raw.CityName",
    "faker.address.raw.CityPrefix",
    "faker.address.raw.CitySuffix",
    "faker.address.raw.CountryCode",
    "faker.address.raw.CountryName",
    "faker.address.raw.Geohash",
    "faker.address.raw.Latitude",
    "faker.address.raw.Longitude",
    "faker.address.raw.PostCode",
    "faker.address.raw.SecondaryAddress",
    "faker.address.raw.SecondaryAddressType",
    "faker.address.raw.StateAbbr",
    "faker.address.raw.StateName",
    "faker.address.raw.StreetName",
    "faker.address.raw.StreetSuffix",
    "faker.address.raw.TimeZone",
    "faker.address.raw.ZipCode",
    "faker.barcode.raw.Isbn",
    "faker.barcode.raw.Isbn10",
    "faker.barcode.raw.Isbn13",
    "faker.boolean.raw.Boolean",
    "faker.chrono.raw.Date",
    "faker.chrono.raw.DateTime",
    "faker.chrono.raw.DateTimeAfter",
    "faker.chrono.raw.DateTimeBefore",
    "faker.chrono.raw.DateTimeBetween",
    "faker.chrono.raw.Duration",
    "faker.chrono.raw.Time",
    "faker.color.raw.Color",
    "faker.color.raw.HexColor",
    "faker.color.raw.HslColor",
    "faker.color.raw.HslaColor",
    "faker.color.raw.RgbColor",
    "faker.color.raw.RgbaColor",
    "faker.company.raw.Bs",
    "faker.company.raw.BsAdj",
    "faker.company.raw.BsNoun",
    "faker.company.raw.BsVerb",
    "faker.company.raw.Buzzword",
    "faker.company.raw.BuzzwordMiddle",
    "faker.company.raw.BuzzwordTail",
    "faker.company.raw.CatchPhrase",
    "faker.company.raw.CompanyName",
    "faker.company.raw.CompanySuffix",
    "faker.company.raw.Industry",
    "faker.company.raw.Profession",
    "faker.creditcard.raw.CreditCardNumber",
    "faker.currency.raw.CurrencyCode",
    "faker.currency.raw.CurrencyName",
    "faker.currency.raw.CurrencySymbol",
    "faker.filesystem.raw.DirPath",
    "faker.filesystem.raw.FileExtension",
    "faker.filesystem.raw.FileName",
    "faker.filesystem.raw.FilePath",
    "faker.filesystem.raw.MimeType",
    "faker.filesystem.raw.Semver",
    "faker.filesystem.raw.SemverStable",
    "faker.filesystem.raw.SemverUnstable",
    "faker.finance.raw.Bic",
    "faker.finance.raw.Isin",
    "faker.http.raw.RfcStatusCode",
    "faker.http.raw.ValidStatusCode",
    "faker.internet.raw.DomainSuffix",
    "faker.internet.raw.FreeEmail",
    "faker.internet.raw.FreeEmailProvider",
    "faker.internet.raw.IP",
    "faker.internet.raw.IPv4",
    "faker.internet.raw.IPv6",
    "faker.internet.raw.MACAddress",
    "faker.internet.raw.Password",
    "faker.internet.raw.SafeEmail",
    "faker.internet.raw.UserAgent",
    "faker.internet.raw.Username",
    "faker.job.raw.Field",
    "faker.job.raw.Position",
    "faker.job.raw.Seniority",
    "faker.job.raw.Title",
    "faker.lorem.raw.Paragraph",
    "faker.lorem.raw.Paragraphs",
    "faker.lorem.raw.Sentence",
    "faker.lorem.raw.Sentences",
    "faker.lorem.raw.Word",
    "faker.lorem.raw.Words",
    "faker.markdown.raw.BlockQuoteMultiLine",
    "faker.markdown.raw.BlockQuoteSingleLine",
    "faker.markdown.raw.BoldWord",
    "faker.markdown.raw.BulletPoints",
    "faker.markdown.raw.Code",
    "faker.markdown.raw.ItalicWord",
    "faker.markdown.raw.Link",
    "faker.markdown.raw.ListItems",
    "faker.name.raw.FirstName",
    "faker.name.raw.LastName",
    "faker.name.raw.Name",
    "faker.name.raw.NameWithTitle",
    "faker.name.raw.Suffix",
    "faker.name.raw.Title",
    "faker.number.raw.Digit",
    "faker.phone_number.raw.CellNumber",
    "faker.phone_number.raw.PhoneNumber",
    "faker.time.raw.Date",
    "faker.time.raw.DateTime",
    "faker.time.raw.DateTimeAfter",
    "faker.time.raw.DateTimeBefore",
    "faker.time.raw.DateTimeBetween",
    "faker.time.raw.Duration",
    "faker.time.raw.Time",
    "semantic.address.building_number",
    "semantic.address.city",
    "semantic.address.country",
    "semantic.address.country_code",
    "semantic.address.postcode",
    "semantic.address.secondary",
    "semantic.address.secondary_type",
    "semantic.address.state",
    "semantic.address.state_abbr",
    "semantic.address.street",
    "semantic.address.street_suffix",
    "semantic.address.timezone",
    "semantic.address.zipcode",
    "semantic.barcode.isbn10",
    "semantic.barcode.isbn13",
    "semantic.color.hex",
    "semantic.color.hsl",
    "semantic.color.rgb",
    "semantic.company.bs",
    "semantic.company.bs_adj",
    "semantic.company.bs_noun",
    "semantic.company.bs_verb",
    "semantic.company.buzzword",
    "semantic.company.catch_phrase",
    "semantic.company.industry",
    "semantic.company.name",
    "semantic.company.profession",
    "semantic.company.suffix",
    "semantic.finance.bic",
    "semantic.finance.currency_code",
    "semantic.finance.currency_name",
    "semantic.finance.currency_symbol",
    "semantic.finance.isin",
    "semantic.http.status_code",
    "semantic.internet.domain_suffix",
    "semantic.internet.free_email_provider",
    "semantic.internet.ipv4",
    "semantic.internet.ipv6",
    "semantic.internet.mac",
    "semantic.internet.password",
    "semantic.internet.user_agent",
    "semantic.lorem.word",
    "semantic.markdown.bold",
    "semantic.markdown.italic",
    "semantic.markdown.link",
    "semantic.person.cell",
    "semantic.person.email",
    "semantic.person.first_name",
    "semantic.person.free_email",
    "semantic.person.last_name",
    "semantic.person.name",
    "semantic.person.phone",
    "semantic.person.suffix",
    "semantic.person.title",
    "semantic.person.username",
    "semantic.time.date",
    "semantic.time.datetime",
];

pub const ALIAS_ENTRIES: &[AliasEntry] = &[
    AliasEntry {
        id: "semantic.address.building_number",
        target: "faker.address.raw.BuildingNumber",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.city",
        target: "faker.address.raw.CityName",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.country",
        target: "faker.address.raw.CountryName",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.country_code",
        target: "faker.address.raw.CountryCode",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.postcode",
        target: "faker.address.raw.PostCode",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.secondary",
        target: "faker.address.raw.SecondaryAddress",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.secondary_type",
        target: "faker.address.raw.SecondaryAddressType",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.state",
        target: "faker.address.raw.StateName",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.state_abbr",
        target: "faker.address.raw.StateAbbr",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.street",
        target: "faker.address.raw.StreetName",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.street_suffix",
        target: "faker.address.raw.StreetSuffix",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.timezone",
        target: "faker.address.raw.TimeZone",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.address.zipcode",
        target: "faker.address.raw.ZipCode",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.barcode.isbn10",
        target: "faker.barcode.raw.Isbn10",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.barcode.isbn13",
        target: "faker.barcode.raw.Isbn13",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.color.hex",
        target: "faker.color.raw.HexColor",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.color.hsl",
        target: "faker.color.raw.HslColor",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.color.rgb",
        target: "faker.color.raw.RgbColor",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.company.bs",
        target: "faker.company.raw.Bs",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.company.bs_adj",
        target: "faker.company.raw.BsAdj",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.company.bs_noun",
        target: "faker.company.raw.BsNoun",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.company.bs_verb",
        target: "faker.company.raw.BsVerb",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.company.buzzword",
        target: "faker.company.raw.Buzzword",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.company.catch_phrase",
        target: "faker.company.raw.CatchPhrase",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.company.industry",
        target: "faker.company.raw.Industry",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.company.name",
        target: "faker.company.raw.CompanyName",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.company.profession",
        target: "faker.company.raw.Profession",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.company.suffix",
        target: "faker.company.raw.CompanySuffix",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.finance.bic",
        target: "faker.finance.raw.Bic",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.finance.currency_code",
        target: "faker.currency.raw.CurrencyCode",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.finance.currency_name",
        target: "faker.currency.raw.CurrencyName",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.finance.currency_symbol",
        target: "faker.currency.raw.CurrencySymbol",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.finance.isin",
        target: "faker.finance.raw.Isin",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.http.status_code",
        target: "faker.http.raw.ValidStatusCode",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.internet.domain_suffix",
        target: "faker.internet.raw.DomainSuffix",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.internet.free_email_provider",
        target: "faker.internet.raw.FreeEmailProvider",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.internet.ipv4",
        target: "faker.internet.raw.IPv4",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.internet.ipv6",
        target: "faker.internet.raw.IPv6",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.internet.mac",
        target: "faker.internet.raw.MACAddress",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.internet.password",
        target: "faker.internet.raw.Password",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.internet.user_agent",
        target: "faker.internet.raw.UserAgent",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.lorem.word",
        target: "faker.lorem.raw.Word",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.markdown.bold",
        target: "faker.markdown.raw.BoldWord",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.markdown.italic",
        target: "faker.markdown.raw.ItalicWord",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.markdown.link",
        target: "faker.markdown.raw.Link",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.person.cell",
        target: "faker.phone_number.raw.CellNumber",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.person.email",
        target: "faker.internet.raw.SafeEmail",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.person.first_name",
        target: "faker.name.raw.FirstName",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.person.free_email",
        target: "faker.internet.raw.FreeEmail",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.person.last_name",
        target: "faker.name.raw.LastName",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.person.name",
        target: "faker.name.raw.Name",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.person.phone",
        target: "faker.phone_number.raw.PhoneNumber",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.person.suffix",
        target: "faker.name.raw.Suffix",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.person.title",
        target: "faker.name.raw.Title",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.person.username",
        target: "faker.internet.raw.Username",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.time.date",
        target: "faker.time.raw.Date",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
    AliasEntry {
        id: "semantic.time.datetime",
        target: "faker.time.raw.DateTime",
        locales: &[LocaleKey::EnUs, LocaleKey::PtBr],
    },
];

pub fn alias_entry(id: &str) -> Option<&'static AliasEntry> {
    ALIAS_ENTRIES.iter().find(|entry| entry.id == id)
}

pub fn generate_value(
    id: &str,
    locale: LocaleKey,
    rng: &mut dyn RngCore,
) -> Option<GeneratedValue> {
    match (id, locale) {
        ("faker.address.raw.BuildingNumber", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::BuildingNumber().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.BuildingNumber", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::BuildingNumber().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.CityName", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::CityName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.CityName", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::CityName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.CityPrefix", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::CityPrefix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.CityPrefix", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::CityPrefix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.CitySuffix", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::CitySuffix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.CitySuffix", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::CitySuffix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.CountryCode", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::CountryCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.CountryCode", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::CountryCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.CountryName", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::CountryName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.CountryName", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::CountryName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.Latitude", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::Latitude().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.Latitude", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::Latitude().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.Longitude", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::Longitude().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.Longitude", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::Longitude().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.PostCode", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::PostCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.PostCode", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::PostCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.SecondaryAddress", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::SecondaryAddress().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.SecondaryAddress", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::SecondaryAddress().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.SecondaryAddressType", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::SecondaryAddressType().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.SecondaryAddressType", LocaleKey::PtBr) => {
            let value: String =
                fake::faker::address::pt_br::SecondaryAddressType().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.StateAbbr", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::StateAbbr().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.StateAbbr", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::StateAbbr().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.StateName", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::StateName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.StateName", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::StateName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.StreetName", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::StreetName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.StreetName", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::StreetName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.StreetSuffix", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::StreetSuffix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.StreetSuffix", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::StreetSuffix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.TimeZone", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::TimeZone().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.TimeZone", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::TimeZone().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.ZipCode", LocaleKey::EnUs) => {
            let value: String = fake::faker::address::en::ZipCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.address.raw.ZipCode", LocaleKey::PtBr) => {
            let value: String = fake::faker::address::pt_br::ZipCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.barcode.raw.Isbn", LocaleKey::EnUs) => {
            let value: String = fake::faker::barcode::en::Isbn().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.barcode.raw.Isbn", LocaleKey::PtBr) => {
            let value: String = fake::faker::barcode::pt_br::Isbn().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.barcode.raw.Isbn10", LocaleKey::EnUs) => {
            let value: String = fake::faker::barcode::en::Isbn10().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.barcode.raw.Isbn10", LocaleKey::PtBr) => {
            let value: String = fake::faker::barcode::pt_br::Isbn10().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.barcode.raw.Isbn13", LocaleKey::EnUs) => {
            let value: String = fake::faker::barcode::en::Isbn13().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.barcode.raw.Isbn13", LocaleKey::PtBr) => {
            let value: String = fake::faker::barcode::pt_br::Isbn13().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.chrono.raw.Date", LocaleKey::EnUs) => {
            let value: String = fake::faker::chrono::en::Date().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.chrono.raw.Date", LocaleKey::PtBr) => {
            let value: String = fake::faker::chrono::pt_br::Date().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.chrono.raw.DateTime", LocaleKey::EnUs) => {
            let value: String = fake::faker::chrono::en::DateTime().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.chrono.raw.DateTime", LocaleKey::PtBr) => {
            let value: String = fake::faker::chrono::pt_br::DateTime().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.chrono.raw.Duration", LocaleKey::EnUs) => {
            let value: chrono::Duration = fake::faker::chrono::en::Duration().fake_with_rng(rng);
            Some(GeneratedValue::Text(value.num_seconds().to_string()))
        }
        ("faker.chrono.raw.Duration", LocaleKey::PtBr) => {
            let value: chrono::Duration = fake::faker::chrono::pt_br::Duration().fake_with_rng(rng);
            Some(GeneratedValue::Text(value.num_seconds().to_string()))
        }
        ("faker.chrono.raw.Time", LocaleKey::EnUs) => {
            let value: String = fake::faker::chrono::en::Time().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.chrono.raw.Time", LocaleKey::PtBr) => {
            let value: String = fake::faker::chrono::pt_br::Time().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.Color", LocaleKey::EnUs) => {
            let value: String = fake::faker::color::en::Color().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.Color", LocaleKey::PtBr) => {
            let value: String = fake::faker::color::pt_br::Color().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.HexColor", LocaleKey::EnUs) => {
            let value: String = fake::faker::color::en::HexColor().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.HexColor", LocaleKey::PtBr) => {
            let value: String = fake::faker::color::pt_br::HexColor().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.HslColor", LocaleKey::EnUs) => {
            let value: String = fake::faker::color::en::HslColor().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.HslColor", LocaleKey::PtBr) => {
            let value: String = fake::faker::color::pt_br::HslColor().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.HslaColor", LocaleKey::EnUs) => {
            let value: String = fake::faker::color::en::HslaColor().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.HslaColor", LocaleKey::PtBr) => {
            let value: String = fake::faker::color::pt_br::HslaColor().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.RgbColor", LocaleKey::EnUs) => {
            let value: String = fake::faker::color::en::RgbColor().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.RgbColor", LocaleKey::PtBr) => {
            let value: String = fake::faker::color::pt_br::RgbColor().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.RgbaColor", LocaleKey::EnUs) => {
            let value: String = fake::faker::color::en::RgbaColor().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.color.raw.RgbaColor", LocaleKey::PtBr) => {
            let value: String = fake::faker::color::pt_br::RgbaColor().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.Bs", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::Bs().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.Bs", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::Bs().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.BsAdj", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::BsAdj().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.BsAdj", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::BsAdj().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.BsNoun", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::BsNoun().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.BsNoun", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::BsNoun().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.BsVerb", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::BsVerb().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.BsVerb", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::BsVerb().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.Buzzword", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::Buzzword().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.Buzzword", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::Buzzword().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.BuzzwordMiddle", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::BuzzwordMiddle().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.BuzzwordMiddle", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::BuzzwordMiddle().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.BuzzwordTail", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::BuzzwordTail().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.BuzzwordTail", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::BuzzwordTail().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.CatchPhrase", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::CatchPhrase().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.CatchPhrase", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::CatchPhrase().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.CompanyName", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::CompanyName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.CompanyName", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::CompanyName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.CompanySuffix", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::CompanySuffix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.CompanySuffix", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::CompanySuffix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.Industry", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::Industry().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.Industry", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::Industry().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.Profession", LocaleKey::EnUs) => {
            let value: String = fake::faker::company::en::Profession().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.company.raw.Profession", LocaleKey::PtBr) => {
            let value: String = fake::faker::company::pt_br::Profession().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.creditcard.raw.CreditCardNumber", LocaleKey::EnUs) => {
            let value: String = fake::faker::creditcard::en::CreditCardNumber().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.creditcard.raw.CreditCardNumber", LocaleKey::PtBr) => {
            let value: String =
                fake::faker::creditcard::pt_br::CreditCardNumber().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.currency.raw.CurrencyCode", LocaleKey::EnUs) => {
            let value: String = fake::faker::currency::en::CurrencyCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.currency.raw.CurrencyCode", LocaleKey::PtBr) => {
            let value: String = fake::faker::currency::pt_br::CurrencyCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.currency.raw.CurrencyName", LocaleKey::EnUs) => {
            let value: String = fake::faker::currency::en::CurrencyName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.currency.raw.CurrencyName", LocaleKey::PtBr) => {
            let value: String = fake::faker::currency::pt_br::CurrencyName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.currency.raw.CurrencySymbol", LocaleKey::EnUs) => {
            let value: String = fake::faker::currency::en::CurrencySymbol().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.currency.raw.CurrencySymbol", LocaleKey::PtBr) => {
            let value: String = fake::faker::currency::pt_br::CurrencySymbol().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.DirPath", LocaleKey::EnUs) => {
            let value: String = fake::faker::filesystem::en::DirPath().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.DirPath", LocaleKey::PtBr) => {
            let value: String = fake::faker::filesystem::pt_br::DirPath().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.FileExtension", LocaleKey::EnUs) => {
            let value: String = fake::faker::filesystem::en::FileExtension().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.FileExtension", LocaleKey::PtBr) => {
            let value: String = fake::faker::filesystem::pt_br::FileExtension().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.FileName", LocaleKey::EnUs) => {
            let value: String = fake::faker::filesystem::en::FileName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.FileName", LocaleKey::PtBr) => {
            let value: String = fake::faker::filesystem::pt_br::FileName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.FilePath", LocaleKey::EnUs) => {
            let value: String = fake::faker::filesystem::en::FilePath().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.FilePath", LocaleKey::PtBr) => {
            let value: String = fake::faker::filesystem::pt_br::FilePath().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.MimeType", LocaleKey::EnUs) => {
            let value: String = fake::faker::filesystem::en::MimeType().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.MimeType", LocaleKey::PtBr) => {
            let value: String = fake::faker::filesystem::pt_br::MimeType().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.Semver", LocaleKey::EnUs) => {
            let value: String = fake::faker::filesystem::en::Semver().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.Semver", LocaleKey::PtBr) => {
            let value: String = fake::faker::filesystem::pt_br::Semver().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.SemverStable", LocaleKey::EnUs) => {
            let value: String = fake::faker::filesystem::en::SemverStable().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.SemverStable", LocaleKey::PtBr) => {
            let value: String = fake::faker::filesystem::pt_br::SemverStable().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.SemverUnstable", LocaleKey::EnUs) => {
            let value: String = fake::faker::filesystem::en::SemverUnstable().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.filesystem.raw.SemverUnstable", LocaleKey::PtBr) => {
            let value: String = fake::faker::filesystem::pt_br::SemverUnstable().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.finance.raw.Bic", LocaleKey::EnUs) => {
            let value: String = fake::faker::finance::en::Bic().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.finance.raw.Bic", LocaleKey::PtBr) => {
            let value: String = fake::faker::finance::pt_br::Bic().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.finance.raw.Isin", LocaleKey::EnUs) => {
            let value: String = fake::faker::finance::en::Isin().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.finance.raw.Isin", LocaleKey::PtBr) => {
            let value: String = fake::faker::finance::pt_br::Isin().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.http.raw.RfcStatusCode", LocaleKey::EnUs) => {
            let value: String = fake::faker::http::en::RfcStatusCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.http.raw.RfcStatusCode", LocaleKey::PtBr) => {
            let value: String = fake::faker::http::pt_br::RfcStatusCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.http.raw.ValidStatusCode", LocaleKey::EnUs) => {
            let value: String = fake::faker::http::en::ValidStatusCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.http.raw.ValidStatusCode", LocaleKey::PtBr) => {
            let value: String = fake::faker::http::pt_br::ValidStatusCode().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.DomainSuffix", LocaleKey::EnUs) => {
            let value: String = fake::faker::internet::en::DomainSuffix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.DomainSuffix", LocaleKey::PtBr) => {
            let value: String = fake::faker::internet::pt_br::DomainSuffix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.FreeEmail", LocaleKey::EnUs) => {
            let value: String = fake::faker::internet::en::FreeEmail().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.FreeEmail", LocaleKey::PtBr) => {
            let value: String = fake::faker::internet::pt_br::FreeEmail().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.FreeEmailProvider", LocaleKey::EnUs) => {
            let value: String = fake::faker::internet::en::FreeEmailProvider().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.FreeEmailProvider", LocaleKey::PtBr) => {
            let value: String =
                fake::faker::internet::pt_br::FreeEmailProvider().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.IP", LocaleKey::EnUs) => {
            let value: String = fake::faker::internet::en::IP().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.IP", LocaleKey::PtBr) => {
            let value: String = fake::faker::internet::pt_br::IP().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.IPv4", LocaleKey::EnUs) => {
            let value: String = fake::faker::internet::en::IPv4().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.IPv4", LocaleKey::PtBr) => {
            let value: String = fake::faker::internet::pt_br::IPv4().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.IPv6", LocaleKey::EnUs) => {
            let value: String = fake::faker::internet::en::IPv6().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.IPv6", LocaleKey::PtBr) => {
            let value: String = fake::faker::internet::pt_br::IPv6().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.MACAddress", LocaleKey::EnUs) => {
            let value: String = fake::faker::internet::en::MACAddress().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.MACAddress", LocaleKey::PtBr) => {
            let value: String = fake::faker::internet::pt_br::MACAddress().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.SafeEmail", LocaleKey::EnUs) => {
            let value: String = fake::faker::internet::en::SafeEmail().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.SafeEmail", LocaleKey::PtBr) => {
            let value: String = fake::faker::internet::pt_br::SafeEmail().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.UserAgent", LocaleKey::EnUs) => {
            let value: String = fake::faker::internet::en::UserAgent().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.UserAgent", LocaleKey::PtBr) => {
            let value: String = fake::faker::internet::pt_br::UserAgent().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.Username", LocaleKey::EnUs) => {
            let value: String = fake::faker::internet::en::Username().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.internet.raw.Username", LocaleKey::PtBr) => {
            let value: String = fake::faker::internet::pt_br::Username().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.job.raw.Field", LocaleKey::EnUs) => {
            let value: String = fake::faker::job::en::Field().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.job.raw.Field", LocaleKey::PtBr) => {
            let value: String = fake::faker::job::pt_br::Field().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.job.raw.Position", LocaleKey::EnUs) => {
            let value: String = fake::faker::job::en::Position().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.job.raw.Position", LocaleKey::PtBr) => {
            let value: String = fake::faker::job::pt_br::Position().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.job.raw.Seniority", LocaleKey::EnUs) => {
            let value: String = fake::faker::job::en::Seniority().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.job.raw.Seniority", LocaleKey::PtBr) => {
            let value: String = fake::faker::job::pt_br::Seniority().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.job.raw.Title", LocaleKey::EnUs) => {
            let value: String = fake::faker::job::en::Title().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.job.raw.Title", LocaleKey::PtBr) => {
            let value: String = fake::faker::job::pt_br::Title().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.lorem.raw.Word", LocaleKey::EnUs) => {
            let value: String = fake::faker::lorem::en::Word().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.lorem.raw.Word", LocaleKey::PtBr) => {
            let value: String = fake::faker::lorem::pt_br::Word().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.markdown.raw.BoldWord", LocaleKey::EnUs) => {
            let value: String = fake::faker::markdown::en::BoldWord().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.markdown.raw.BoldWord", LocaleKey::PtBr) => {
            let value: String = fake::faker::markdown::pt_br::BoldWord().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.markdown.raw.ItalicWord", LocaleKey::EnUs) => {
            let value: String = fake::faker::markdown::en::ItalicWord().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.markdown.raw.ItalicWord", LocaleKey::PtBr) => {
            let value: String = fake::faker::markdown::pt_br::ItalicWord().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.markdown.raw.Link", LocaleKey::EnUs) => {
            let value: String = fake::faker::markdown::en::Link().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.markdown.raw.Link", LocaleKey::PtBr) => {
            let value: String = fake::faker::markdown::pt_br::Link().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.FirstName", LocaleKey::EnUs) => {
            let value: String = fake::faker::name::en::FirstName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.FirstName", LocaleKey::PtBr) => {
            let value: String = fake::faker::name::pt_br::FirstName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.LastName", LocaleKey::EnUs) => {
            let value: String = fake::faker::name::en::LastName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.LastName", LocaleKey::PtBr) => {
            let value: String = fake::faker::name::pt_br::LastName().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.Name", LocaleKey::EnUs) => {
            let value: String = fake::faker::name::en::Name().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.Name", LocaleKey::PtBr) => {
            let value: String = fake::faker::name::pt_br::Name().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.NameWithTitle", LocaleKey::EnUs) => {
            let value: String = fake::faker::name::en::NameWithTitle().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.NameWithTitle", LocaleKey::PtBr) => {
            let value: String = fake::faker::name::pt_br::NameWithTitle().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.Suffix", LocaleKey::EnUs) => {
            let value: String = fake::faker::name::en::Suffix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.Suffix", LocaleKey::PtBr) => {
            let value: String = fake::faker::name::pt_br::Suffix().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.Title", LocaleKey::EnUs) => {
            let value: String = fake::faker::name::en::Title().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.name.raw.Title", LocaleKey::PtBr) => {
            let value: String = fake::faker::name::pt_br::Title().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.number.raw.Digit", LocaleKey::EnUs) => {
            let value: String = fake::faker::number::en::Digit().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.number.raw.Digit", LocaleKey::PtBr) => {
            let value: String = fake::faker::number::pt_br::Digit().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.phone_number.raw.CellNumber", LocaleKey::EnUs) => {
            let value: String = fake::faker::phone_number::en::CellNumber().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.phone_number.raw.CellNumber", LocaleKey::PtBr) => {
            let value: String = fake::faker::phone_number::pt_br::CellNumber().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.phone_number.raw.PhoneNumber", LocaleKey::EnUs) => {
            let value: String = fake::faker::phone_number::en::PhoneNumber().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.phone_number.raw.PhoneNumber", LocaleKey::PtBr) => {
            let value: String = fake::faker::phone_number::pt_br::PhoneNumber().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.time.raw.Date", LocaleKey::EnUs) => {
            let value: String = fake::faker::time::en::Date().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.time.raw.Date", LocaleKey::PtBr) => {
            let value: String = fake::faker::time::pt_br::Date().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.time.raw.DateTime", LocaleKey::EnUs) => {
            let value: String = fake::faker::time::en::DateTime().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.time.raw.DateTime", LocaleKey::PtBr) => {
            let value: String = fake::faker::time::pt_br::DateTime().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.time.raw.Duration", LocaleKey::EnUs) => {
            let value: time::Duration = fake::faker::time::en::Duration().fake_with_rng(rng);
            Some(GeneratedValue::Text(value.whole_seconds().to_string()))
        }
        ("faker.time.raw.Duration", LocaleKey::PtBr) => {
            let value: time::Duration = fake::faker::time::pt_br::Duration().fake_with_rng(rng);
            Some(GeneratedValue::Text(value.whole_seconds().to_string()))
        }
        ("faker.time.raw.Time", LocaleKey::EnUs) => {
            let value: String = fake::faker::time::en::Time().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        ("faker.time.raw.Time", LocaleKey::PtBr) => {
            let value: String = fake::faker::time::pt_br::Time().fake_with_rng(rng);
            Some(GeneratedValue::Text(value))
        }
        _ => None,
    }
}
